### ISSUE TITLE
the package named positional-1.1.1.tar.gz may not be found in https://pypi.python.org/simple/pbr/.

### ISSUE THREAD

**Issue by smalljiaotongxue** [Huawei/python-openstacksdk#1]
**url:**
https://huawei.github.io/python-openstacksdk/#/zh-cn/quickstart

**command:**
pip install -r requirements.txt

**cause:**
the package named positional-1.1.1.tar.gz may not be found in https://pypi.python.org/simple/pbr/.

**error log:**
Collecting pbr!=2.1.0,>=2.0.0 (from -r requirements.txt (line 4))
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Collecting jsonpatch>=1.1 (from -r requirements.txt (line 5))
  Using cached jsonpatch-1.16-py2.py3-none-any.whl
Collecting six>=1.9.0 (from -r requirements.txt (line 6))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting stevedore>=1.20.0 (from -r requirements.txt (line 7))
  Using cached stevedore-1.23.0-py2.py3-none-any.whl
Collecting os-client-config>=1.27.0 (from -r requirements.txt (line 8))
  Using cached os_client_config-1.27.0-py2.py3-none-any.whl
Collecting keystoneauth1>=2.20.0 (from -r requirements.txt (line 9))
  Using cached keystoneauth1-2.21.0-py2.py3-none-any.whl
Collecting deprecation>=1.0 (from -r requirements.txt (line 10))
  Using cached deprecation-1.0.1.tar.gz
Collecting jsonpointer>=1.9 (from jsonpatch>=1.1->-r requirements.txt (line 5))
  Using cached jsonpointer-1.10-py2-none-any.whl
Collecting PyYAML>=3.1.0 (from os-client-config>=1.27.0->-r requirements.txt (line 8))
  Using cached PyYAML-3.12.tar.gz
Collecting requestsexceptions>=1.1.1 (from os-client-config>=1.27.0->-r requirements.txt (line 8))
  Using cached requestsexceptions-1.2.0-py2.py3-none-any.whl
Collecting appdirs>=1.3.0 (from os-client-config>=1.27.0->-r requirements.txt (line 8))
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
Collecting positional>=1.1.1 (from keystoneauth1>=2.20.0->-r requirements.txt (line 9))
  Using cached positional-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/pbr/: [Errno 101] Network is unreachable -- Some packages may not be found!
    Couldn't find index page for 'pbr' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno 101] Network is unreachable -- Some packages may not be found!
    No local packages or working download links found for pbr>=1.8
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5a3tWC/positional/setup.py", line 26, in <module>
        pbr=True)
      File "/usr/local/python2.7.12/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 320, in __init__
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 377, in fetch_build_eggs
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 852, in resolve
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1124, in best_match
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1136, in obtain
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 445, in fetch_build_egg
      File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 667, in easy_install
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr>=1.8')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5a3tWC/positional/

**Comment by IamFive** [comment]
是不是你的网络环境有限制呢

**Comment by IamFive** [comment]
你试一下使用国内的 douban 的 pypi 镜像。

```
pip install -r requirements.txt -i https://pypi.douban.com/simple
```

**Comment by smalljiaotongxue** [comment]
https://pypi.douban.com/simple  豆瓣这个访问会直接报错。

错误日志：
Collecting pbr!=2.1.0,>=2.0.0 (from -r requirements.txt (line 4))
  Could not fetch URL https://pypi.douban.com/simple/pbr/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement pbr!=2.1.0,>=2.0.0 (from -r requirements.txt (line 4)) (from versions: )
No matching distribution found for pbr!=2.1.0,>=2.0.0 (from -r requirements.txt (line 4))

https://pypi.python.org/simple/pbr/  这个从日志来看，前几条都未报错，等using cached positional-1.1.1.tar.gz的时候才报错。


另外这个链接在浏览器可以直接被打开并且有内容（https://pypi.python.org/simple/pbr/ ），豆瓣的链接确实被华为禁掉了。

**Comment by IamFive** [comment]
出错的地方是：

```
Complete output from command python setup.py egg_info:
Download error on https://pypi.python.org/simple/pbr/: [Errno 101] Network is unreachable -- Some packages may not be found!
Couldn't find index page for 'pbr' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [Errno 101] Network is unreachable -- Some packages may not be found!
No local packages or working download links found for pbr>=1.8
```

很明显是 network 连接出问题了。

**Comment by IamFive** [comment]
从你的日志来看是 使用的 linux 服务器吗，是的话，试下配置一下 `~/.pip/pip.conf `

```
root@VM-245-70-ubuntu:~# cat ~/.pip/pip.conf 
[global]
timeout = 6000
trusted-host = pypi.douban.com
index-url = http://pypi.douban.com/simple/
```

**Comment by smalljiaotongxue** [comment]
目前豆瓣是直接被禁掉，添加配置也没有用，我先申请一下访问豆瓣的网权。

**Comment by IamFive** [comment]
ok，或者问下原来测试 python-openstackclient的同事是怎么安装依赖的。
