### ISSUE TITLE
【CES】查询指标列表metrics接口缺少start参数，参数dimensions要改为dim。请参照标准接口文档进行命名修改。

### ISSUE THREAD

**Issue by smalljiaotongxue** [Huawei/python-openstacksdk#14]
名称 | 是否必选 | 参数类型 | 说明
-- | -- | -- | --
namespace | 否 | 字符串 | 指标命名空间，例如弹性云服务器命名空间。
metric_name | 否 | 字符串 | 指标名称，例如弹性云服务器监控指标中的cpu_util。
dim | 否 | 字符串 | 指标的维度，目前最大支持3个维度，从0开始；维度格式为dim.{i}=key,value，参考弹性云服务器维度。
  例如：dim.0=instance_id,6f3c6f91-4b24-4e1b-b7d1-a94ac1cb011d
start | 否 | 字符串 | 分页起始值，格式为：namespace.metric_name.key:value
  例如：start=SYS.ECS.cpu_util.instance_id:d9112af5-6913-4f3b-bd0a-3f96711e004d
limit | 否 | 整数 | 取值范围(0,1000]，默认值为1000。
  用于限制结果数据条数。
order | 否 | 枚举 | 用于标识结果排序方法。
  取值说明，默认为desc：
  l 
  asc，升序
  l 
  desc，降序

**Comment by IamFive** [comment]
没有start，叫做 marker

**Comment by IamFive** [comment]
dimension 那边是对参数命名做了调整，明显调整后的参数格式更加符合使用习惯。。

**Comment by IamFive** [comment]
我们这基本不会对参数做大改动，除非是一些很不合理的地方，会稍微调整下。

**Comment by smalljiaotongxue** [comment]
我起初认为参数命名最好保持一致，这样我们就只用维护一份标准的接口参考文档即可。这个就先不改了吧，首要保证功能，再保证易用性吧。

**Comment by IamFive** [comment]
是的能维持一致是最好的，但是想 dim.0 这种，用户根本没法用。肯定是传 list 比较好用。

**Comment by IamFive** [comment]
从使用方便角度出发，不然我们费劲改这个干嘛 :)
