### ISSUE TITLE
【DNS服务】执行functional test中的test_zone.py，提示No handlers could be found for logger "openstack.connection"

### ISSUE THREAD

**Issue by dnstester** [Huawei/python-openstacksdk#18]
具体提示内容如下：
No handlers could be found for logger "openstack.connection"
C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

如何解决？

**Comment by dnstester** [comment]
公网不需要绑定VPC

**Comment by IamFive** [comment]
这个是。。logging 的设置问题，属于python语法的范畴。感兴趣可以看下 run_example.py 中的代码

**Comment by IamFive** [comment]
还是说你问的是  `HTTPS` ? 那个你们环境的问题，就那样。
