### ISSUE TITLE
[DNS服务]执行test_zone.py，提示'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by dnstester** [Huawei/python-openstacksdk#20]
Error
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\tests\functional\dns\v2\test_zone.py", line 76, in setUpClass
    cls.zone = auto_create_private_zone(cls.conn, cls.NAME, cls.router.id,
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by dnstester** [comment]
调试后提示：router.gi_frame.__internals__['f_lasti'] = {AttributeError}'frame' object has no attribute '__internals__',如何解决？

**Comment by dnstester** [comment]
此问题已解决
请更新代码openstack/NETWORK/v2/router.py
将base_path = '/routers' = 'routers'改为base_path = '/vpcs'
将resource_key = 'router'改为resource_key = 'vpc'
   resources_key改为resources_key = 'vpcs'

**Comment by IamFive** [comment]
别改原生的代码。这个地方是有撒问题吗？

**Comment by IamFive** [comment]
![image](https://user-images.githubusercontent.com/1578702/28248030-fcdfa354-6a6e-11e7-8db1-196002a97908.png)

**Comment by IamFive** [comment]
德电环境 那个测试用例可以直接跑，他是一个完整的流程。从创建查询绑定解绑删除 都有涉及到。

**Comment by dnstester** [comment]
请问下，VPC服务相关接口的代码在哪？不是network么？

**Comment by IamFive** [comment]
https://github.com/Huawei/python-openstacksdk/blob/master/openstack/tests/functional/dns/v2/test_ptr.py#L39

是 network，OTC上有些地方有调整，不过基本都是概念上的调整（名称），实际接口都是跟原生一致的。

**Comment by IamFive** [comment]
https://github.com/Huawei/python-openstacksdk/blob/master/openstack/tests/functional/dns/v2/test_zone.py#L46

**Comment by IamFive** [comment]
你说的那些都是不能改的，其他很多地方都有关联到。。

**Comment by dnstester** [comment]
我在类生产上跑用例，必须知道VPC的os.environ.setdefault，我翻阅代码发现改network，如果不是，我应该改那部分？

**Comment by dnstester** [comment]
可是VPC的接口文档里，查询url为GET /v1/{tenant_id}/vpcs，没有routers啊

**Comment by IamFive** [comment]
本地环境的token信息如果有问题的话，可以设置如下环境变量。
VPC是在原生openstack服务上改的（原生的才是真正实现的地方），vpc只是个包装的名字，实际的接口应该是有的，你试试看。

```
        os.environ.setdefault(
            'OS_NETWORK_ENDPOINT_OVERRIDE',
            '改成你的地址'
        )
```

**Comment by dnstester** [comment]
恩，我就是这样设置的，我应该是把地址写成内部调用的地址了，应该是对外地址，我再改回来试试，谢谢

**Comment by IamFive** [comment]
sdk已有的代码不要去动他，就算没有，也是手动去管理后台拿，改代码是不行的。改一下，所有的测试用例，已有的功能测试代码等等全部都有可能挂掉。

**Comment by IamFive** [comment]
还有其他工具依赖这个SDK的。也会挂掉

**Comment by dnstester** [comment]
好的，我知道了
