### ISSUE TITLE
【DNS服务】执行test_ptr.py时，调用EIP接口错误

### ISSUE THREAD

**Issue by dnstester** [Huawei/python-openstacksdk#23]
经查VPC API相关文档，查询EIP的接口是GET v2/{tenant_id}/publicips,所以需要修改以下内容：
openstack/NETWORK/v2/floating_ip.py中class FloatingIP(resource.Resource):
resource_key = 'floatingip'改为"publicip"
    resources_key = 'floatingips'改为"publicips"
    base_path = '/floatingips'改为"/publicips"

添加public_ip_address = resource.Body('public_ip_address')
将name = floating_ip_address改为name = public_ip_address

修改后，测试代码通过，请更新下代码

**Comment by IamFive** [comment]
已有的模块代码我们这不会去动到的。 floatingip 有 floating ip 的用处，而且有很多地方都已经用到这个了。

test_ptr.py 还是 test_zone.py 都是可以直接在 德电环境上成功运行的。我没理解你改这个是为撒。

**Comment by IamFive** [comment]
duplicate with issue #21
