### ISSUE TITLE
[DNS服务]查询zonelistURI，缺少type参数

### ISSUE THREAD

**Issue by dnstester** [Huawei/python-openstacksdk#26]
def test_2_list_zone(self):
        zones = list(self.conn.dns.zones(limit=50))
        found = False
        for zone in zones:
            if zone.id == self.zone.id:
                found = True
        self.assertTrue(found)

不好意思，之前漏掉了，API的格式为GET /v2/zones?type={public}&limit={limit}&marker={marker}，但python的代码中缺少type参数

**Comment by IamFive** [comment]
这个是文档有误，实际叫做 `zone_type` 。其实一开始设计的时候，是叫做 `type`，后来忘记是撒原因又改回 zone_type 了，我把它改成两个都支持的吧。

**Comment by IamFive** [comment]
汗，看错了，文档里面是type。想起来原因了，因为zone创建的时候，这个字段叫做 `zone_type`，但是查询的时候叫做 `type`，搞混掉了。重新更新下。
