### ISSUE TITLE
【AS】1.3.1	查询弹性伸缩策略列表文档有误，缺group_id;

### ISSUE THREAD

**Issue by caoyameng** [Huawei/python-openstacksdk#27]
1.3.1	查询弹性伸缩策略列表
query = {
    "name": "as_policy_name",
    "type": "ALARM",                # ALARM, SCHEDULED, RECURRENCE
    "marker": 0,
    "limit": 20
}
policies = conn.auto_scaling.policies(**query)
for policy in policies:
    logging.info(policy)

**Comment by IamFive** [comment]
有这个查询参数，`scaling_group_id`

**Comment by IamFive** [comment]
文档上加了。
