### ISSUE TITLE
【AS】修改伸缩策略，请求体有问题

### ISSUE THREAD

**Issue by caoyameng** [Huawei/python-openstacksdk#28]
HttpException: HttpException: request body error (HTTP 400), [AS.0022] request body error

代码：
    def test_modify_policy(self):
        new_policy_name = "as-policy-name"
        _policy = {
            # "scaling_policy_name": "policy_01",
            # "scaling_policy_type": "RECURRENCE",
            # "scheduled_policy": {
            #     "launch_time": "16:00",
            #     "recurrence_type": "Daily",
            #     "recurrence_value": None,
            #     "end_time": "2018-02-08T17:31Z",
            #     "start_time": "2017-08-08T17:31Z"
            # },
            # "scaling_policy_action": {
            #     "operation": "SET",
            #     "instance_number": 2
            # },
            "cool_down_time": 300
        }
        to_update_policy_id = "401da127-fb96-4e9c-af88-6b5824c74bb8"
        policy = self.conn.auto_scaling.update_policy(to_update_policy_id, **_policy)
        policy = self.conn.auto_scaling.get_policy(policy)
        # logging.info(policy)
        print(policy)

**Comment by IamFive** [comment]
我这测试没问题诶

**Comment by IamFive** [comment]
能把你的请求发送的内容 粘贴上来吗

**Comment by caoyameng** [comment]
我重新更新了代码，OK了
