### ISSUE TITLE
【AS】查询伸缩组日志，limit没起作用

### ISSUE THREAD

**Issue by caoyameng** [Huawei/python-openstacksdk#30]

**Comment by caoyameng** [comment]
之前没注意，怎么测了好几个，limit像是都没起作用啊

**Comment by IamFive** [comment]
稍等，我看下。

**Comment by IamFive** [comment]
不是 limit 没生效，所有的 list 请求在 openstacksdk 里面都是 一个 python generator，在访问超出limit范围的数据时，会自动给你翻页去请求下一页的数据。

**Comment by IamFive** [comment]
你把log打开就知道了。你limit=1的话，每一条数据都会有一个请求到服务器。
