### ISSUE TITLE
【DNS】缺少查询版本号相关用例（Python、JAVA）

### ISSUE THREAD

**Issue by dnstester** [Huawei/python-openstacksdk#31]

**Comment by IamFive** [comment]
文档上并没有版本号相关的API啊。

**Comment by dnstester** [comment]
API文档里面有啊

**Comment by dnstester** [comment]
云解析服务版本管理

**Comment by IamFive** [comment]
23 | DNS | POST   /v2/zones | Create   zone
-- | -- | -- | --
24 | DNS | GET   /v2/zones/{zone_id} | Show   zone
25 | DNS | GET   /v2/zones | List   zone
26 | DNS | DELETE   /v2/zones/{zone_id} | Delete   zone
27 | DNS | POST   /v2/zones/{zone_id}/recordsets | Create   Recordset
28 | DNS | GET   /v2/zone/{zone_id}/recordsets/{recordset_id} | Show   a Recordset
29 | DNS | GET   /v2/recordsets | List   all Recordsets
30 | DNS | GET   /v2/zones/{zone_id}/recordsets | List   Recordsets in a Zone
31 | DNS | DELETE    /v2/zones/{zone_id}/recordsets/{recordset_id} | Delete   a Recordset
32 | DNS | PATCH    /v2/reverse/floatingips/{region}:{floatingip_id} | Set   floatingip ptr record
33 | DNS | PATCH    /v2/reverse/floatingips/{region}:{floatingip_id} | Unset   floatingip ptr record
34 | DNS | GET   /v2/reverse/floatingips | List   floatingip ptr records
35 | DNS | GET   /v2/reverse/floatingips/{region}:{floatingip_id} | Show   floatingip ptr record details

**Comment by IamFive** [comment]
要实现的API是在 需求任务书里面，不是根据API文档来的。

**Comment by dnstester** [comment]
好的
