### ISSUE TITLE
【VBS】利用不可备份的类型卷创建备份

### ISSUE THREAD

**Issue by tunsuy** [Huawei/python-openstacksdk#33]
比如：使用超高IO类型的某卷创建备份

返回如下错误：
```python
openstack.exceptions.SDKException: Unable to establish connection
```

应该是返回具体的错误码及错误
应该是这个：
```python
[VolumeBackup.0086] shared volume does not support backup
```

**Comment by IamFive** [comment]
我要怎么重现。你把完整的http请求日志发上来看下。

`openstack.exceptions.SDKException: Unable to establish connection` 这个异常正常是指 连接失败，根本没连到服务器的。

**Comment by IamFive** [comment]
如果服务端返回的状态码 是400以上的，异常处理过程是通用的。

**Comment by IamFive** [comment]
长时间未回复，关闭issue
