### ISSUE TITLE
[DNS]请提供下API与SDK的对应关系

### ISSUE THREAD

**Issue by dnstester** [Huawei/python-openstacksdk#38]

**Comment by IamFive** [comment]
Interface | method | API URL
-- | -- | --
Zone | create_zone(self, **attrs) | POST /v2/zones
get_zone(self, zone) | GET /v2/zones/{zone_id}
zones(self, **query) | GET /v2/zones
delete_zone(self, zone,   ignore_missing=True) | DELETE /v2/zones/{zone_id}
nameservers(self, zone) | GET /v2/zones/{zone_id}/nameservers
add_router_to_zone(self, zone,   **router) | POST /v2/zones/{zone_id}/associaterouter
remove_router_from_zone(self, zone, **router) | POST /v2/zones/{zone_id}/disassociaterouter
Recordset | create_recordset(self, zone, **attrs) | POST /v2/zones/{zone_id}/recordsets
get_recordset(self, zone, recordset) | GET /v2/zone/{zone_id}/recordsets/{recordset_id}
all_recordsets(self, **query) | GET /v2/recordsets
recordsets(self, zone, **query) | GET /v2/zones/{zone_id}/recordsets
PTR Record | delete_recordset(self, zone, recordset, ignore_missing=True) | DELETE    /v2/zones/{zone_id}/recordsets/{recordset_id}
create_ptr(self, **attrs) | PATCH    /v2/reverse/floatingips/{region}:{floatingip_id}
restore_ptr(self, region,   floating_ip_id) | PATCH    /v2/reverse/floatingips/{region}:{floatingip_id}
ptrs(self, **query) | GET /v2/reverse/floatingips
get_ptr(self, region,   floating_ip_id) | GET /v2/reverse/floatingips/{region}:{floatingip_id}

**Comment by IamFive** [comment]
贴不了，找张栋要，提供过了
