### ISSUE TITLE
【KMS】返回异常不够详细

### ISSUE THREAD

**Issue by sl061201124** [Huawei/python-openstacksdk#39]
当使用KMS创建用户主密钥，密钥别名已存在时，期望返回异常详情为
{"error":{"error_code":"KMS.1104","error_msg":"The key alias already exists (0X00060018)."}}
而当前返回的异常信息为Bad Request (HTTP 400)，过于笼统，可否改进？

**Comment by IamFive** [comment]
收到 已安排开发确认

**Comment by IamFive** [comment]
你好 确认下，你测试的是java版本还是 python版本？

issue是不是建错地方了，这个项目是python版本的，KMS不在本次开发的范围内。

**Comment by sl061201124** [comment]
我说的就是python版，Java版不存在这个问题


发自我的 iPhone

**Comment by IamFive** [comment]
python openstack sdk 本次开发的需求里面没有包含 KMS 服务，请确认。

**Comment by IamFive** [comment]
你是不是测试的 openstackclient的项目？ 就是通过命令行调用KMS服务的。
