### ISSUE TITLE
【KMS】加密数据密钥接口入参plain_text应带hash值

### ISSUE THREAD

**Issue by sl061201124** [Huawei/python-openstacksdk#40]
为简化用户使用，应将计算hash值在sdk内部完成，而非用户自己处理，可参考如下:

    hash=hashlib.sha256()
    hex_data=str(datakey.plain_text).decode("hex")
    hash.update(bytearray(hex_data))
    digest=hash.hexdigest()
    plain_text=key.plain_text+digest
    params = {
        "plain_text": plain_text,
        "datakey_plain_length": "64"
    }

**Comment by IamFive** [comment]
本次开发的需求里 未包含 KMS 服务，请确认下issue是不是建错地方了。
