### ISSUE TITLE
[DNS]recordset查询接口变更，旧接口无法正确获取正确结果 

### ISSUE THREAD

**Issue by dnstester** [Huawei/python-openstacksdk#50]
1.查询单个Zone下Record Set列表
接口变更为：GET /v2/zones/{zone_id}/recordsets?limit={limit}&marker={marker}

2.查询Record Set列表
接口变更为：GET /v2/recordsets?zone_type={zone_type}&limit={limit}&marker={marker}

**Comment by IamFive** [comment]
还有这种操作，新更新接口不兼容旧的。
能一起整理下吗，哪些有变更的一并处理，如果多的话，还要跟张栋确认。

**Comment by IamFive** [comment]
能提供下完整的文档吗，zone-type 是什么 （private/public） ? 还是 A，CNAME，MX 那些。

看不懂这API设计的目的，正常用户查记录，是查某个Zone下，某个类型的吧。

**Comment by dnstester** [comment]
待查询的Record Set的域名类型。
取值范围：public、private
l 如果为空，表示查询公网类型的
Record Set。
l 如果为public，表示查询公网类型
的Record Set。
l 如果为private

**Comment by IamFive** [comment]
> 1.查询单个Zone下Record Set列表
> 接口变更为：GET /v2/zones/{zone_id}/recordsets?limit={limit}&marker={marker}

这个接口是不是有问题，查不出数据。

**Comment by dnstester** [comment]
1.查询单个Zone下Record Set列表
 接口变更为：GET /v2/zones/{zone_id}/recordsets?limit={limit}&marker={marker}
这个接口并为改变
查不出数据原因：接口没有问题，但是在APIGATEWAY那注册后，映射的接口不对，目前映射到GET v2/recordsets上了，服务组正在定位，修改为GET /v2.1/zones/{zone_id}/recordsets?zone_type="private"&limit={limit}&marker={marker}，查询正常

**Comment by IamFive** [comment]
我这边要做撒修改吗？我先提交代码上来？

**Comment by dnstester** [comment]
仅修改查询Record Set列表即可
 接口变更为：GET /v2/recordsets?zone_type={zone_type}&limit={limit}&marker={marker}

**Comment by IamFive** [comment]
还有你这个issue是针对java版本的吧？ python好像很早前修复过了。

**Comment by IamFive** [comment]
java 和 python 版本都已修订
