### ISSUE TITLE
函数参数描述接口有误

### ISSUE THREAD

**Issue by awesome2012** [Huawei/python-openstacksdk#55]
remove_members_of_listener函数描述有问题，members这个参数，应该传入的是member_id，而不是server id，麻烦修改一下

**Comment by IamFive** [comment]
是那一段有问题呢，注释看起来是没问题的。并且事实上member-id也就是server-id。

```
 def remove_members_of_listener(self, listener, members):
        """Remove backend members for a listener

        :param listener: Either the ID of a listener or an instance of
                :class:`~openstack.load_balancer.v1.listener.Listener`
        :param members: member list to be removed from listener,
            list of members (ECS server id) belongs to the listener
            ["dbecb618-2259-405f-ab17-9b68c4f541b0",] for example.

        :return: a operate member job
        :rtype: :class:`~openstack.load_balancer.v1.listener.OperateMemberJob`
        """
        listener = self._get_resource(_listener.Listener, listener)
        return listener.remove_members(self._session, members)
```

**Comment by IamFive** [comment]
tenant_id | 是 | String | 操作用户的租户ID。
-- | -- | -- | --
listener_id | 是 | String | 监听器的ID。
removeMember | 是 | 列表数据结构 | 移除的后端云服务器信息列表。

**Comment by awesome2012** [comment]
server_address | String | 后端云服务器私网IP。
-- | -- | --
id | String | 后端云服务器ID。
address | String | 分配给后端云服务器的浮动IP。
status | String | 后端云服务器状态。状态值：ACTIVE，PENDING，ERROR。
health_status | String | 健康检查状态。状态值：NORMAL，ABNORMAL，UNAVAILABLE。
update_time | String | 更新时间。
create_time | String | 创建时间。
server_name | String | 后端云服务器名称。
server_id | String | 原始云服务器ID。
listeners | 列表数据结构 | 后端云服务器所属监听器。

后端云服务器ID就是指的是member的ID哦，这个接口应该没怎么改过，如果以前是传的server-id的话，麻烦你现在改成member id

**Comment by IamFive** [comment]
ok。
