### ISSUE TITLE
[DNS服务]python-Unittest中response缺少links和metadata要素参数相关的定义和匹配

### ISSUE THREAD

**Issue by dnstester** [Huawei/python-openstacksdk#7]
【测试路径】
openstack/test/unit/dns/v2/test_proxy.py

【测试发现的问题】
Unittest中response缺少links和metadata要素参数相关的定义和匹配，例如：查询PTR Record列表GET /v2/reverse/floatingips?limit={limit}&marker={marker}，它的response要素包括links、metadata、floatingips，但test_list_zones(self)中没有相关的匹配代码

【改进建议】
请确认是否需要加上links、metadata要素的判断

**Comment by IamFive** [comment]
不需要。这些数据对用户来说没有实际意义，所有原声的实现都一样没有这些数据。
